version: "3.8"
services:
  nuxt-my-app:
    build: .
    image: node:erbium-alpine3.14
    command: [
        "sh",
        "-c",
        "
        npm run build && npm run prod
        ",
      ]
    volumes:
      - .:/usr/src/docker-teste
    working_dir: /usr/src/docker-teste
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
