version: "3.8"
services:  
  app:
    build: .
    image: node:erbium-alpine3.14
    command: npm run prod
    volumes:
        - .:/app
    working_dir: /app  
    ports:
        - "3000:3000"
    environment: 
        - HOST=0.0.0.0
        - PORT=3000